name: morse_code
description: "This app should take a phrase and at the touch of a button should make the led on the phone flash the morse code for that phrase. It should also display the code for a certain character when the led is flashing it. The app should also be able to send that code via sms. Also, the app should be able to decrypt the received sms."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_sms: ^2.0.0
  permission_handler: ^12.0.0+1
  torch_light: ^1.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
